import { Html, Head, Main, NextScript } from "next/document";

import React from "react";

export default function Document() {
  return (
    <Html lang="fa">
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="breakpoint">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
