import type { NextPage } from "next";
import Head from "next/head";
import Swipper from "../components/sliders/Swipper";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>فروشگاه بیوتی | صفحه اصلی</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Swipper />
    </>
  );
};

export default Home;
